name: Test Project
on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with: 
            node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Execute Tests
        run: npm run test
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-files
          path: |
            coverage/lcov-report
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with: 
          name: coverage-files
          path: docs
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      - name: Set Git configuration
        run: |
          git config pull.rebase false
      - name: Push to GitHub Pages Branch
        run: |
          git checkout -b gh-pages
          git pull --allow-unrelated-histories origin gh-pages
          git add .
          git commit -m "Update coverage files"
          git push origin gh-pages